"""Shared test fixtures."""

import pytest
import pandas as pd


@pytest.fixture
def sample_events_df():
    """A small DataFrame of parsed port-visit events for testing."""
    return pd.DataFrame([
        {
            "event_id": "evt1",
            "visit_id": "v1",
            "confidence": 4,
            "vessel_id": "vid1",
            "vessel_name": "MAERSK ALPHA",
            "vessel_mmsi": "123456789",
            "vessel_flag": "DNK",
            "vessel_type": "CONTAINER",
            "start": "2024-03-01T08:00:00Z",
            "end": "2024-03-02T20:00:00Z",
            "duration_hours": 36.0,
            "port_name": "SINGAPORE",
            "port_id": "p1",
            "port_flag": "SGP",
            "at_dock": False,
            "anchorage_id": "a1",
            "end_port_name": "SINGAPORE",
            "end_port_id": "p1",
            "lat": 1.25,
            "lon": 103.8,
            "matched_label": "SINGAPORE",
            "matched_is_dock": False,
            "matched_iso3": "SGP",
            "vessel_category": "Container",
            "tonnage_gt": 120000,
            "size_class": "Very Large",
        },
        {
            "event_id": "evt2",
            "visit_id": "v2",
            "confidence": 3,
            "vessel_id": "vid2",
            "vessel_name": "EAGLE TANKER",
            "vessel_mmsi": "987654321",
            "vessel_flag": "LBR",
            "vessel_type": "TANKER",
            "start": "2024-04-10T12:00:00Z",
            "end": "2024-04-12T06:00:00Z",
            "duration_hours": 42.0,
            "port_name": "WEST JURONG",
            "port_id": "p2",
            "port_flag": "SGP",
            "at_dock": True,
            "anchorage_id": "a2",
            "end_port_name": "WEST JURONG",
            "end_port_id": "p2",
            "lat": 1.28,
            "lon": 103.7,
            "matched_label": "WEST JURONG",
            "matched_is_dock": True,
            "matched_iso3": "SGP",
            "vessel_category": "Tanker",
            "tonnage_gt": 85000,
            "size_class": "Very Large",
        },
        {
            "event_id": "evt3",
            "visit_id": "v3",
            "confidence": 4,
            "vessel_id": "vid3",
            "vessel_name": "BULK STAR",
            "vessel_mmsi": "111222333",
            "vessel_flag": "PAN",
            "vessel_type": "BULK_CARRIER",
            "start": "2024-05-01T00:00:00Z",
            "end": "2024-05-03T12:00:00Z",
            "duration_hours": 60.0,
            "port_name": "SINGAPORE",
            "port_id": "p1",
            "port_flag": "SGP",
            "at_dock": False,
            "anchorage_id": "a3",
            "end_port_name": "SINGAPORE",
            "end_port_id": "p1",
            "lat": 1.26,
            "lon": 103.81,
            "matched_label": "SINGAPORE",
            "matched_is_dock": False,
            "matched_iso3": "SGP",
            "vessel_category": "Bulk Carrier",
            "tonnage_gt": 45000,
            "size_class": "Large",
        },
        {
            "event_id": "evt4",
            "visit_id": "v4",
            "confidence": 2,
            "vessel_id": "vid4",
            "vessel_name": "SMALL FERRY",
            "vessel_mmsi": "444555666",
            "vessel_flag": "SGP",
            "vessel_type": "FERRY",
            "start": "2024-06-15T06:00:00Z",
            "end": "2024-06-15T10:00:00Z",
            "duration_hours": 4.0,
            "port_name": "CHANGI",
            "port_id": "p3",
            "port_flag": "SGP",
            "at_dock": True,
            "anchorage_id": "a4",
            "end_port_name": "CHANGI",
            "end_port_id": "p3",
            "lat": 1.35,
            "lon": 104.0,
            "matched_label": "CHANGI",
            "matched_is_dock": True,
            "matched_iso3": "SGP",
            "vessel_category": "Passenger",
            "tonnage_gt": 2000,
            "size_class": "Small",
        },
    ])


@pytest.fixture
def sample_raw_events():
    """Sample raw GFW event dicts (API response format)."""
    return [
        {
            "id": "evt1",
            "vessel": {
                "id": "vid1",
                "name": "MAERSK ALPHA",
                "ssvid": "123456789",
                "flag": "DNK",
                "type": "CONTAINER",
            },
            "position": {"lat": 1.25, "lon": 103.8},
            "start": "2024-03-01T08:00:00Z",
            "end": "2024-03-02T20:00:00Z",
            "port_visit": {
                "visitId": "v1",
                "confidence": 4,
                "durationHrs": 36.0,
                "startAnchorage": {
                    "name": "SINGAPORE",
                    "id": "p1",
                    "flag": "SGP",
                    "atDock": False,
                    "anchorageId": "a1",
                    "topDestination": "SINGAPORE",
                },
                "endAnchorage": {
                    "name": "SINGAPORE",
                    "id": "p1",
                },
                "intermediateAnchorage": {},
            },
        },
    ]
